app = "go-extract"
primary_region = "sin"

[build.args]
GO_VERSION = "1.23.5"

[env]
PORT = "8989"

[http_service]
auto_start_machines = true
auto_stop_machines = true
force_https = true
internal_port = 8989
min_machines_running = 0
processes = [ "app" ]

[[vm]]
  size = 'shared-cpu-1x'